ANDROID: KVM: arm64: Fix GCC warning in pkvm_get_guest_pa_request()
GCC is being picky about the usage of parentheses in certain conditions:

	arch/arm64/kvm/hyp/nvhe/mem_protect.c: In function ‘pkvm_get_guest_pa_request’:
	arch/arm64/kvm/hyp/nvhe/mem_protect.c:1928:49: error: suggest parentheses around ‘-’ in operand of ‘&’ [-Werror=parentheses]
		 1928 |  *out_pa |= (ipa & kvm_granule_size(*out_level) - 1) & PAGE_MASK;

Add the parentheses to silence the warning.

Bug: 357781595
Bug: 348382247
Bug: 236685427
Bug: 458241298
Fixes: d826ecccde3c ("ANDROID: KVM: arm64: Generalize guest PA query")
Change-Id: I83f345aac0315092037a89abf8dc67c3f39e0428
Signed-off-by: Quentin Perret <qperret@google.com>